import React, { useMemo } from 'react';
import { useNavigate } from 'react-router-dom';
import { useQuery } from '@apollo/client';
import styled from 'styled-components';
import { Button } from '../../components/Button';
import { GET_LOANS, GET_PORTFOLIO_SUMMARY } from '../../graphql/operations/loans';
import { formatCurrency, formatDate } from '../../utils/formatters';
import { KpiCard } from './KpiCard';
import { MonthlyInterestChart } from './MonthlyInterestChart';

const RECENT_LIMIT = 5;
const yieldFormatter = new Intl.NumberFormat('en-US', {
  style: 'percent',
  minimumFractionDigits: 1,
  maximumFractionDigits: 1,
});

interface MonthlyInterestPoint {
  month: string;
  interest: number;
}

interface PortfolioSummaryData {
  portfolioSummary: {
    totalLoans: number;
    totalPrincipal: number;
    totalExpectedInterest: number;
    activeLoans: number;
    monthlyInterestTimeline: MonthlyInterestPoint[];
  };
}

interface RecentLoan {
  id: string;
  name: string;
  principal: number;
  startDate: string;
  endDate: string;
  totalExpectedInterest: number;
}

interface GetLoansData {
  loans: {
    loans: RecentLoan[];
    total: number;
    page: number;
    pageSize: number;
  };
}

export function StatisticsPage() {
  const navigate = useNavigate();

  const { data: summaryData, loading: summaryLoading } = useQuery<PortfolioSummaryData>(
    GET_PORTFOLIO_SUMMARY,
    { fetchPolicy: 'cache-and-network' },
  );

  const {
    data: loansData,
    loading: loansLoading,
    error: loansError,
    refetch: refetchLoans,
  } = useQuery<GetLoansData>(GET_LOANS, {
    variables: { page: 1, pageSize: RECENT_LIMIT },
    fetchPolicy: 'cache-and-network',
  });

  const summary = summaryData?.portfolioSummary ?? null;
  const showStatPlaceholders = summaryLoading && !summaryData;

  const kpis = useMemo(
    () => [
      {
        id: 'total-loans',
        label: 'Total Loans',
        value: summary === null ? '-' : summary.totalLoans.toLocaleString(),
        hint: 'Active loans',
      },
      {
        id: 'total-principal',
        label: 'Total Principal',
        value: summary === null ? '-' : formatCurrency(summary.totalPrincipal),
        hint: 'Outstanding principal exposure',
      },
      {
        id: 'expected-interest',
        label: 'Total Expected Interest',
        value: summary === null ? '-' : formatCurrency(summary.totalExpectedInterest),
        hint: 'Total projected interest',
      },
    ],
    [summary],
  );

  const chartData = useMemo(() => {
    if (!summary?.monthlyInterestTimeline) {
      return [];
    }

    return [...summary.monthlyInterestTimeline].sort((a, b) => a.month.localeCompare(b.month));
  }, [summary]);

  const averageLoanSize =
    summary && summary.totalLoans > 0 ? summary.totalPrincipal / summary.totalLoans : null;
  const averageInterestPerLoan =
    summary && summary.totalLoans > 0 ? summary.totalExpectedInterest / summary.totalLoans : null;
  const interestYield =
    summary && summary.totalPrincipal > 0 ? summary.totalExpectedInterest / summary.totalPrincipal : null;

  const loans = loansData?.loans.loans ?? [];
  const hasLoans = loans.length > 0;
  const loansBlockLoading = loansLoading && !loansData;

  return (
    <Container>
      <PageHeader>
        <div>
          <PageTitle>Statistics</PageTitle>
          <PageSubtitle>Portfolio insights and repayment performance.</PageSubtitle>
        </div>
      </PageHeader>

      <Section>
        <SectionEyebrow>Key metrics</SectionEyebrow>
        <SectionHeading>Current portfolio position</SectionHeading>
        <KpiGrid>
          {kpis.map((kpi) => (
            <KpiCard
              key={kpi.id}
              label={kpi.label}
              value={kpi.value}
              hint={kpi.hint}
              loading={showStatPlaceholders}
            />
          ))}
        </KpiGrid>
      </Section>

      <DashboardGrid>
        <ChartSection>
          <PanelHeader>
            <PanelTitle>Monthly Interest Over Time</PanelTitle>
            <PanelSubtitle>Total expected interest generated by schedule month</PanelSubtitle>
          </PanelHeader>
          <MonthlyInterestChart data={chartData} />
        </ChartSection>

        <InsightsSection>
          <PanelHeader>
            <PanelTitle>Portfolio Insights</PanelTitle>
            <PanelSubtitle>Fast read on portfolio quality</PanelSubtitle>
          </PanelHeader>
          <InsightsList>
            <InsightItem>
              <InsightLabel>Active loans</InsightLabel>
              <InsightValue>
                {summary === null ? '-' : summary.activeLoans.toLocaleString()}
              </InsightValue>
            </InsightItem>
            <InsightItem>
              <InsightLabel>Average loan size</InsightLabel>
              <InsightValue>
                {averageLoanSize === null ? '-' : formatCurrency(averageLoanSize)}
              </InsightValue>
            </InsightItem>
            <InsightItem>
              <InsightLabel>Average interest per loan</InsightLabel>
              <InsightValue>
                {averageInterestPerLoan === null ? '-' : formatCurrency(averageInterestPerLoan)}
              </InsightValue>
            </InsightItem>
            <InsightItem>
              <InsightLabel>Interest yield</InsightLabel>
              <InsightValue>{interestYield === null ? '-' : yieldFormatter.format(interestYield)}</InsightValue>
            </InsightItem>
          </InsightsList>
        </InsightsSection>
      </DashboardGrid>

      <RecentSection>
        <RecentHeader>
          <div>
            <RecentTitle>Recent Loans</RecentTitle>
            <RecentSubtitle>Most recent portfolio activity (up to 5 loans)</RecentSubtitle>
          </div>
          {hasLoans && (
            <Button $variant="ghost" $size="sm" onClick={() => navigate('/loans')}>
              View all loans →
            </Button>
          )}
        </RecentHeader>

        {loansBlockLoading ? (
          <LoadingState>Loading loans…</LoadingState>
        ) : loansError ? (
          <ErrorState>
            <ErrorTitle>Couldn&apos;t load loans</ErrorTitle>
            <ErrorDescription>
              The backend didn&apos;t respond. Check your connection and try again.
            </ErrorDescription>
            <Button $variant="secondary" $size="sm" onClick={() => void refetchLoans()}>
              Retry
            </Button>
          </ErrorState>
        ) : hasLoans ? (
          <RecentList>
            {loans.map((loan) => (
              <RecentRow key={loan.id} type="button" onClick={() => navigate(`/loan/${loan.id}`)}>
                <RecentPrimary>
                  <RecentName>{loan.name}</RecentName>
                  <RecentMeta>
                    {formatDate(loan.startDate)} → {formatDate(loan.endDate)}
                  </RecentMeta>
                </RecentPrimary>
                <RecentNumbers>
                  <RecentAmount>{formatCurrency(loan.principal)}</RecentAmount>
                  <RecentInterest>{formatCurrency(loan.totalExpectedInterest)} interest</RecentInterest>
                </RecentNumbers>
                <RowChevron aria-hidden="true">→</RowChevron>
              </RecentRow>
            ))}
          </RecentList>
        ) : (
          <EmptyState>
            <EmptyIconWrap aria-hidden="true">
              <DocumentIcon />
            </EmptyIconWrap>
            <EmptyTitle>No loans yet</EmptyTitle>
            <EmptyDescription>
              Create your first bullet loan to generate a repayment schedule and start tracking
              principal and interest.
            </EmptyDescription>
            <Button onClick={() => navigate('/loans')}>Go to Loans</Button>
          </EmptyState>
        )}
      </RecentSection>
    </Container>
  );
}

const Container = styled.div`
  max-width: 1200px;
  margin: 0 auto;
  padding: ${({ theme }) => theme.spacing.xl};
  display: flex;
  flex-direction: column;
  gap: ${({ theme }) => theme.spacing.xl};

  @media (max-width: ${({ theme }) => theme.breakpoints.md}) {
    padding: ${({ theme }) => theme.spacing.lg} ${({ theme }) => theme.spacing.md};
    gap: ${({ theme }) => theme.spacing.lg};
  }
`;

const PageHeader = styled.div`
  margin-bottom: -${({ theme }) => theme.spacing.xs};
`;

const PageTitle = styled.h1`
  margin: 0 0 2px;
  font-size: ${({ theme }) => theme.typography.fontSize.xl};
  font-weight: ${({ theme }) => theme.typography.fontWeight.bold};
  color: ${({ theme }) => theme.colors.textPrimary};
  letter-spacing: -0.01em;
`;

const PageSubtitle = styled.p`
  margin: 0;
  font-size: ${({ theme }) => theme.typography.fontSize.sm};
  color: ${({ theme }) => theme.colors.textMuted};
`;

const Section = styled.section``;

const SectionEyebrow = styled.p`
  margin: 0 0 ${({ theme }) => theme.spacing.xs};
  font-size: ${({ theme }) => theme.typography.fontSize.xs};
  font-weight: ${({ theme }) => theme.typography.fontWeight.semibold};
  color: ${({ theme }) => theme.colors.primary};
  letter-spacing: 1.2px;
  text-transform: uppercase;
`;

const SectionHeading = styled.h2`
  margin: 0 0 ${({ theme }) => theme.spacing.md};
  font-size: ${({ theme }) => theme.typography.fontSize.lg};
  font-weight: ${({ theme }) => theme.typography.fontWeight.bold};
  color: ${({ theme }) => theme.colors.textPrimary};
  letter-spacing: -0.01em;
`;

const KpiGrid = styled.div`
  display: grid;
  grid-template-columns: repeat(3, minmax(0, 1fr));
  gap: ${({ theme }) => theme.spacing.md};

  @media (max-width: ${({ theme }) => theme.breakpoints.md}) {
    grid-template-columns: 1fr;
  }
`;

const DashboardGrid = styled.section`
  display: grid;
  grid-template-columns: minmax(0, 2fr) minmax(280px, 1fr);
  gap: ${({ theme }) => theme.spacing.md};
  align-items: stretch;

  @media (max-width: ${({ theme }) => theme.breakpoints.md}) {
    grid-template-columns: 1fr;
  }
`;

const ChartSection = styled.article`
  background: ${({ theme }) => theme.colors.surface};
  border: 1px solid ${({ theme }) => theme.colors.border};
  border-radius: ${({ theme }) => theme.radius.lg};
  box-shadow: ${({ theme }) => theme.shadow.sm};
  padding: ${({ theme }) => theme.spacing.lg};
  transition:
    box-shadow 0.12s ease,
    transform 0.12s ease;

  &:hover {
    box-shadow: ${({ theme }) => theme.shadow.md};
    transform: translateY(-1px);
  }
`;

const InsightsSection = styled.aside`
  background: ${({ theme }) => theme.colors.surface};
  border: 1px solid ${({ theme }) => theme.colors.border};
  border-radius: ${({ theme }) => theme.radius.lg};
  box-shadow: ${({ theme }) => theme.shadow.sm};
  padding: ${({ theme }) => theme.spacing.lg};
  transition:
    box-shadow 0.12s ease,
    transform 0.12s ease;

  &:hover {
    box-shadow: ${({ theme }) => theme.shadow.md};
    transform: translateY(-1px);
  }
`;

const PanelHeader = styled.div`
  margin-bottom: ${({ theme }) => theme.spacing.md};
`;

const PanelTitle = styled.h3`
  margin: 0 0 2px;
  font-size: ${({ theme }) => theme.typography.fontSize.md};
  font-weight: ${({ theme }) => theme.typography.fontWeight.semibold};
  color: ${({ theme }) => theme.colors.textPrimary};
`;

const PanelSubtitle = styled.p`
  margin: 0;
  font-size: ${({ theme }) => theme.typography.fontSize.sm};
  color: ${({ theme }) => theme.colors.textMuted};
`;

const InsightsList = styled.div`
  display: flex;
  flex-direction: column;
  gap: ${({ theme }) => theme.spacing.xs};
`;

const InsightItem = styled.div`
  border: 1px solid ${({ theme }) => theme.colors.border};
  border-radius: ${({ theme }) => theme.radius.md};
  padding: ${({ theme }) => theme.spacing.md} ${({ theme }) => theme.spacing.sm};
  background: ${({ theme }) => theme.colors.surface};
  display: flex;
  align-items: baseline;
  justify-content: space-between;
  gap: ${({ theme }) => theme.spacing.sm};
`;

const InsightLabel = styled.p`
  margin: 0;
  font-size: ${({ theme }) => theme.typography.fontSize.sm};
  font-weight: ${({ theme }) => theme.typography.fontWeight.medium};
  color: ${({ theme }) => theme.colors.textSecondary};
`;

const InsightValue = styled.p`
  margin: 0;
  font-size: ${({ theme }) => theme.typography.fontSize.md};
  font-weight: ${({ theme }) => theme.typography.fontWeight.bold};
  color: ${({ theme }) => theme.colors.textPrimary};
  font-variant-numeric: tabular-nums;
  text-align: right;
`;

const RecentSection = styled.section`
  background: ${({ theme }) => theme.colors.surface};
  border: 1px solid ${({ theme }) => theme.colors.border};
  border-radius: ${({ theme }) => theme.radius.lg};
  box-shadow: ${({ theme }) => theme.shadow.sm};
  overflow: hidden;
`;

const RecentHeader = styled.div`
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  gap: ${({ theme }) => theme.spacing.md};
  padding: ${({ theme }) => theme.spacing.lg};
  border-bottom: 1px solid ${({ theme }) => theme.colors.border};
`;

const RecentTitle = styled.h2`
  margin: 0 0 2px;
  font-size: ${({ theme }) => theme.typography.fontSize.lg};
  font-weight: ${({ theme }) => theme.typography.fontWeight.semibold};
  color: ${({ theme }) => theme.colors.textPrimary};
`;

const RecentSubtitle = styled.p`
  margin: 0;
  font-size: ${({ theme }) => theme.typography.fontSize.sm};
  color: ${({ theme }) => theme.colors.textMuted};
`;

const RecentList = styled.div`
  display: flex;
  flex-direction: column;
`;

const RecentRow = styled.button`
  display: grid;
  grid-template-columns: minmax(0, 1fr) auto auto;
  align-items: center;
  column-gap: ${({ theme }) => theme.spacing.md};
  width: 100%;
  padding: ${({ theme }) => theme.spacing.md} ${({ theme }) => theme.spacing.lg};
  background: transparent;
  border: 0;
  text-align: left;
  cursor: pointer;
  transition:
    background 0.12s ease,
    transform 0.12s ease;
  font-family: inherit;

  & + & {
    border-top: 1px solid ${({ theme }) => theme.colors.border};
  }

  &:hover {
    background: ${({ theme }) => theme.colors.background};
    transform: translateX(1px);
  }

  &:focus-visible {
    outline: 2px solid ${({ theme }) => theme.colors.primary};
    outline-offset: -2px;
  }

  @media (max-width: ${({ theme }) => theme.breakpoints.sm}) {
    grid-template-columns: 1fr;
    row-gap: ${({ theme }) => theme.spacing.xs};
  }
`;

const RecentPrimary = styled.div`
  min-width: 0;
`;

const RecentName = styled.span`
  display: block;
  margin-bottom: 2px;
  font-size: ${({ theme }) => theme.typography.fontSize.base};
  font-weight: ${({ theme }) => theme.typography.fontWeight.semibold};
  color: ${({ theme }) => theme.colors.textPrimary};
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
`;

const RecentMeta = styled.span`
  font-size: ${({ theme }) => theme.typography.fontSize.sm};
  color: ${({ theme }) => theme.colors.textMuted};
`;

const RecentNumbers = styled.div`
  display: flex;
  flex-direction: column;
  align-items: flex-end;
  gap: 2px;

  @media (max-width: ${({ theme }) => theme.breakpoints.sm}) {
    align-items: flex-start;
  }
`;

const RecentAmount = styled.span`
  font-size: ${({ theme }) => theme.typography.fontSize.base};
  font-weight: ${({ theme }) => theme.typography.fontWeight.semibold};
  color: ${({ theme }) => theme.colors.textPrimary};
  font-variant-numeric: tabular-nums;
`;

const RecentInterest = styled.span`
  font-size: ${({ theme }) => theme.typography.fontSize.xs};
  color: ${({ theme }) => theme.colors.textMuted};
  font-variant-numeric: tabular-nums;
`;

const RowChevron = styled.span`
  color: ${({ theme }) => theme.colors.textMuted};
  font-size: ${({ theme }) => theme.typography.fontSize.base};
  transition:
    transform 0.12s ease,
    color 0.12s ease;

  ${RecentRow}:hover & {
    transform: translateX(1px);
    color: ${({ theme }) => theme.colors.textSecondary};
  }

  @media (max-width: ${({ theme }) => theme.breakpoints.sm}) {
    display: none;
  }
`;

const EmptyState = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  text-align: center;
  padding: ${({ theme }) => theme.spacing.xxl} ${({ theme }) => theme.spacing.lg};
  gap: ${({ theme }) => theme.spacing.xs};
`;

const EmptyIconWrap = styled.div`
  color: ${({ theme }) => theme.colors.textMuted};
  margin-bottom: ${({ theme }) => theme.spacing.xs};
`;

const EmptyTitle = styled.p`
  margin: 0;
  font-size: ${({ theme }) => theme.typography.fontSize.md};
  font-weight: ${({ theme }) => theme.typography.fontWeight.semibold};
  color: ${({ theme }) => theme.colors.textPrimary};
`;

const EmptyDescription = styled.p`
  font-size: ${({ theme }) => theme.typography.fontSize.sm};
  color: ${({ theme }) => theme.colors.textSecondary};
  max-width: 360px;
  margin: 0 0 ${({ theme }) => theme.spacing.sm};
`;

const LoadingState = styled.div`
  padding: ${({ theme }) => theme.spacing.xxl};
  text-align: center;
  color: ${({ theme }) => theme.colors.textMuted};
  font-size: ${({ theme }) => theme.typography.fontSize.sm};
`;

const ErrorState = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  text-align: center;
  padding: ${({ theme }) => theme.spacing.xxl} ${({ theme }) => theme.spacing.lg};
  gap: ${({ theme }) => theme.spacing.sm};
`;

const ErrorTitle = styled.p`
  margin: 0;
  font-size: ${({ theme }) => theme.typography.fontSize.md};
  font-weight: ${({ theme }) => theme.typography.fontWeight.semibold};
  color: ${({ theme }) => theme.colors.textPrimary};
`;

const ErrorDescription = styled.p`
  margin: 0;
  font-size: ${({ theme }) => theme.typography.fontSize.sm};
  color: ${({ theme }) => theme.colors.textSecondary};
  max-width: 360px;
`;

function DocumentIcon() {
  return (
    <svg
      width="40"
      height="40"
      viewBox="0 0 40 40"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden="true"
    >
      <rect x="7" y="5" width="26" height="30" rx="3" stroke="currentColor" strokeWidth="1.75" />
      <line x1="13" y1="14" x2="27" y2="14" stroke="currentColor" strokeWidth="1.75" strokeLinecap="round" />
      <line x1="13" y1="20" x2="27" y2="20" stroke="currentColor" strokeWidth="1.75" strokeLinecap="round" />
      <line x1="13" y1="26" x2="21" y2="26" stroke="currentColor" strokeWidth="1.75" strokeLinecap="round" />
    </svg>
  );
}
